### ISSUE TITLE
Soft hyphens?

### ISSUE THREAD

**Issue by Quuxplusone** [mmastrac/gibbet-hill#2]
It'd be nice to have a version of story.md without the line-break-hyphens included (e.g. "attention" instead of "at- tention").
This could either be a wholly separate .md file (probably the path of least resistance), or you could try playing around with [soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) or maybe there's something Markdown-specific that could help. I'm not sure if it'll actually Just Work to replace every line-breaking `-` with `&x00AD;` but it's worth a shot. Or if that fails, it might still Just Work to replace every line-breaking `-` with the UTF-8 for U+00AD.

**Comment by mmastrac** [comment]
That's a good idea -- ideally we'd linebreak the whole story approximately at the same place as the newspaper columns (to better proof), but without the soft-hyphens and allow markdown to render HTML without those breaks.

I don't think we need a separate .md file for it -- the soft hyphens are a rendering artifact of them medium and can definitely be stripped out.

**Comment by mmastrac** [comment]
These should be removed now.
